# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Site Scan Dashboard
email: site-scanning@gsa.gov
description: >- # this means to ignore newlines until "baseurl:"
  See the results of the site-scanning project here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 18F
github_username:  18F

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# This is the URL for the site-scanner UI and API.  Make sure it ends in /.
scanner_url: https://scanner-ui-patient-chipmunk.app.cloud.gov/

# This is the list of domains which we want to be displayed.
domainlist:
  - presidentialinnovationfellows.gov
  - cloud.gov
  - challenge.gov
  - digital.gov
  - fedramp.gov
  - usa.gov
  - search.gov
  - kids.gov
  - gobiernousa.gov
  - login.gov
  - 18f.gov
  - data.gov
  - vote.gov
  - citizenscience.gov

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# This is for federalist, so it will relaunch it nightly
schedule: 'nightly'
