# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Site Scan Dashboard
email: site-scanning@gsa.gov
description: >- # this means to ignore newlines until "baseurl:"
  See the results of the site-scanning project here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 18F
github_username:  18F

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

domaingroups:
  - presidentialinnovationfellows.gov
  - cloud.gov
  - challenge.gov
  - digital.gov
  - fedramp.gov
  - usa.gov
  - search.gov
  - kids.gov
  - gobiernousa.gov
  - login.gov
  - 18f.gov
  - data.gov
  - vote.gov
  - citizenscience.gov

jekyll_get:
  - data: presidentialinnovationfellows.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/presidentialinnovationfellows.gov/'
    cache: true
  - data: cloud.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/cloud.gov/'
    cache: true
  - data: challenge.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/challenge.gov/'
    cache: true
  - data: digital.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/digital.gov/'
    cache: true
  - data: fedramp.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/fedramp.gov/'
    cache: true
  - data: usa.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/usa.gov/'
    cache: true
  - data: search.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/search.gov/'
    cache: true
  - data: kids.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/kids.gov/'
    cache: true
  - data: gobiernousa.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/gobiernousa.gov/'
    cache: true
  - data: login.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/login.gov/'
    cache: true
  - data: 18f.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/18f.gov/'
    cache: true
  - data: data.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/data.gov/'
    cache: true
  - data: vote.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/vote.gov/'
    cache: true
  - data: citizenscience.gov
    json: 'https://scanner-ui-patient-chipmunk.app.cloud.gov/api/v1/domains/citizenscience.gov/'
    cache: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
